package org.example.model;

public class User {
    private int id;
    private String name;
    private String email;

    // Constructor for creating a new User (ID will be auto-generated by DB)
    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

    // Constructor for retrieving an existing User (ID is known)
    public User(int id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    // Setters (useful for updates, or if ID is set after insertion)
    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
